version: '3.4'
volumes:
  kong_data: {}

networks: #Red interna para comunicar los servicios (“Services on the same network can communicate with each other using their name”)
  kong-net:

services:
  api-user:
    image: api-user-image
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8083:8083
    networks: # Networks to join
      - kong-net
